# Generated by Django 4.1.5 on 2023-01-12 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveIntegerField(help_text='What would you like to start the item price at (Whole dollars only, maximum of 100000)', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
